<div id=":mn" class="a3s aiL ">
    <div class="adM"></div>
    <div>
        <div class="adM"></div>
        <table cellspacing="0" cellpadding="0" border="0"
               style="color:#172b4d;background:#fff;padding:0;margin:0;width:100%;font:15px 'Helvetica Neue',Arial,Helvetica">
            <tbody>
            <tr width="100%">
                <td valign="top" align="left" style="background:#fff;font:15px 'Helvetica Neue',Arial,Helvetica">
                    <table style="border:none;padding:0 18px;margin:50px auto;width:500px;border-spacing:0px">
                        <tbody>

                        <tr width="100%" height="57">
                            <td valign="top" align="left"
                                style="border-top-left-radius:4px;border-top-right-radius:4px;background:#fff;padding:12px 18px;text-align:center">

                                <img height="25" width="122"
                                     src="../static/js/trello_icon.png"
                                     title="Trello"
                                     style="font-weight:bold;font-size:18px;color:#0079bf;vertical-align:top"
                                     class="CToWUd" data-bit="iit"></td>
                        </tr>

                        <tr style="width:100%">
                            <td valign="top" align="left" style="background:#fff;padding:18px">

                                <p style="color:#172b4d;font:14px/1.25em 'Helvetica Neue',
                                Arial,Helvetica;font-weight:bold;line-height:20px;text-align:center;padding-left:56px;padding-right:56px" >
                                    Hey there! from Developers co has invited you to their
                                    Workspace on Trello<span>.</span></p>

                                <div width="100%" style="overflow:visible;height:24px" align="center"><img
                                            style="border-radius:50%;vertical-align:bottom;object-fit:cover" width="48"
                                            height="48"
                                            src="https://ci3.googleusercontent.com/proxy/f_6MCNxZNVslepmPNLwaMZXu6fK6R5GK5PuFD12hrdyJTKf1VnzhBo57wJZAFL7qaC_BPK3GNxWv--6UJKYI_tZMMT1xm-TSrSxcxBUyunA0XC8hgyRuGpB-NIoS8xpjqcKBh7JggwDJqvosAJzu91WEaPynDp9Fms91bg=s0-d-e1-ft#https://trello-members.s3.amazonaws.com/62a879caccfbc53570f49804/67df2da5ca6d50c625ee9ac87b775375/170.png"
                                            class="CToWUd" data-bit="iit"></div>

                                <div style="background:#fff;border:solid 1px #c1c7d0;margin-left:56px;margin-right:56px;border-radius:3px">
                                    <p style="color:#172b4d;line-height:20px;text-align:center;margin:0;font-style:italic;padding-left:24px;padding-right:24px;padding-top:32px;padding-bottom:17px">
                                        "Join this Trello Workspace to start collaborating with me!" </p></div>

                                <p style="font:15px/1.25em 'Helvetica Neue',Arial,Helvetica;margin-bottom:0;text-align:center">
                                    <a href="https://id.atlassian.com/login?application=trello&amp;continue=https%3A%2F%2Ftrello.com%2Fauth%2Fatlassian%2Fcallback%3FreturnUrl%3D%252Forg%252F62a9b54cfae4df507c46ac54%26display%3D%26aaOnboarding%3D%26updateEmail%3D%26traceId%3D%26migrateGoogle%3D%26ssoVerified%3D&amp;email=muhammadqodiryusupov6%40gmail.com&amp;restrict=true"
                                       style="border-radius:3px;background:#5aac44;color:#fff;display:block;font-weight:600;font-size:20px;line-height:24px;margin:32px auto 24px;padding:11px 13px;text-decoration:none;width:152px"
                                       target="_blank"
                                       data-saferedirecturl="https://www.google.com/url?q=https://id.atlassian.com/login?application%3Dtrello%26continue%3Dhttps%253A%252F%252Ftrello.com%252Fauth%252Fatlassian%252Fcallback%253FreturnUrl%253D%25252Forg%25252F62a9b54cfae4df507c46ac54%2526display%253D%2526aaOnboarding%253D%2526updateEmail%253D%2526traceId%253D%2526migrateGoogle%253D%2526ssoVerified%253D%26email%3Dmuhammadqodiryusupov6%2540gmail.com%26restrict%3Dtrue&amp;source=gmail&amp;ust=1661532564392000&amp;usg=AOvVaw1q4xsuUmm7HXisKMiG7MtA">
                                        Join the Workspace </a></p>

                                <p style="font:14px/1.25em 'Helvetica Neue',Arial,Helvetica;color:#838c91;text-align:center;padding-left:56px;padding-right:56px;padding-bottom:8px">
                                    Trello boards help you put your plans into action and achieve your goals. <a
                                            href="http://trello.com" style="color:#0079bf;text-decoration:none"
                                            target="_blank"
                                            data-saferedirecturl="https://www.google.com/url?q=http://trello.com&amp;source=gmail&amp;ust=1661532564392000&amp;usg=AOvVaw2FQpc_2VDxqTjF_FlJ6BJF">Learn
                                        more</a></p>

                            </td>
                        </tr>

                        </tbody>
                    </table>
                </td>
            </tr>
            </tbody>
        </table>
        <img border="0" width="1" height="1" alt=""
             src="https://ci3.googleusercontent.com/proxy/slCSL3vm4gJVYDBODlkusi1sO_YPEMD2t6uafyRbcUy3g7QA2VLALJF7XS2qrq786N-aWKXLGvYQC28HPr3CxPVDEl5_6dP5b9U2HE38Q7O3qsyEXwaQ3ORUeBm8dLN0UavEf83ru2INxZ-4tn83QcupnScEaspZlootwm4fAL9fJVDhskpcePxLGq5IiRjs3C0dIet4U7F9svHWwvJ7H8kA65B9AoMG6dt-aBcUWbF1qA=s0-d-e1-ft#http://sptrack.trello.com/q/uv-7pzyOLwJZMCvTjaBgMg~~/AAAAAQA~/RgRk5xtVPlcLYXRsYXNzaWFudXNCCmLy1ecFYyyMSgBSH211aGFtbWFkcW9kaXJ5dXN1cG92NkBnbWFpbC5jb21YBAAAAAM~"
             class="CToWUd" data-bit="iit">
        <div class="yj6qo"></div>
        <div class="adL">
        </div>
    </div>
    <div class="adL">

    </div>
</div>